'use strict';
// Bundle the dependency-free static analyzer (parser + charset + analyze) into a
// single browser file exposing window.redosray = { findCandidates, parse, shapeOf }.
// Dynamic confirmation runs in the page via a Web Worker (see docs/index.html),
// mirroring the Node worker_threads approach used by the CLI.
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'src');
const OUT = path.join(__dirname, '..', 'docs', 'redosray.browser.js');

const files = ['parser.js', 'charset.js', 'analyze.js', 'extract.js'];

function moduleName(f) { return f.replace(/\.js$/, ''); }

let body = '';
for (const f of files) {
  let code = fs.readFileSync(path.join(SRC, f), 'utf8');
  // Rewrite relative requires: require('./parser') -> require('parser')
  code = code.replace(/require\(\s*['"]\.\/([^'"]+)['"]\s*\)/g, "require('$1')");
  body += `\ndefine('${moduleName(f)}', function(module, exports, require){\n${code}\n});\n`;
}

const bundle = `/* redosray browser bundle — generated by scripts/build-browser.js. Do not edit by hand. */
(function (global) {
  'use strict';
  var __modules = {};
  var __cache = {};
  function define(name, factory) { __modules[name] = factory; }
  function require(name) {
    if (__cache[name]) return __cache[name].exports;
    var m = { exports: {} };
    __cache[name] = m;
    __modules[name](m, m.exports, require);
    return m.exports;
  }
${body}
  var analyze = require('analyze');
  var extract = require('extract');
  global.redosray = {
    findCandidates: analyze.findCandidates,
    parse: analyze.parse,
    shapeOf: analyze.shapeOf,
    extractFromText: extract.extractFromText,
    languageForPath: extract.languageForPath,
    CLASS_BY_KIND: {
      'nested-quantifier': 'exponential',
      'ambiguous-alternation': 'exponential',
      'sequential-quantifier': 'polynomial'
    }
  };
})(typeof self !== 'undefined' ? self : this);
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, bundle);
console.log('Wrote', OUT, '(' + bundle.length + ' bytes)');
